# Generated by Django 3.0 on 2019-12-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='spray label')),
                ('date_added', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
