# Generated by Django 3.0 on 2019-12-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spray',
            name='num_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spray',
            name='date_added',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='spray',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Spray Label'),
        ),
    ]
