# Generated by Django 3.0 on 2019-12-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray', '0002_auto_20191210_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spray',
            name='num_frames',
            field=models.IntegerField(default=0, verbose_name='Number of Frames'),
        ),
    ]
