# Generated by Django 3.0 on 2020-01-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray', '0004_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droplets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Droplet Label')),
                ('date_added', models.DateTimeField(verbose_name='Date Published')),
                ('perimeter', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Perimeter')),
                ('density', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='density')),
                ('area', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Area')),
                ('mass', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Mass')),
            ],
        ),
    ]
